services:
  db:
    image: postgres:17
    container_name: task_manager_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
